"""Operator's switchboard — web UI for gradphone.

Two roles, one dashboard template:

- **Operator** logs in at /ui/login with BRIDGE_API_KEY. Unrestricted view
  of all tenants + ability to manage tenants (deactivate, override quota).
- **Tenant** lands via /ui/auth?token=<magic-link>. Sees only their own
  calls and quota. Dial form auto-scopes to their tenant_id.

Magic links are generated by the Telegram bot's /web command (the bot
signs them with the shared BRIDGE_API_KEY so the bridge can verify
them). Links expire in 5 minutes; the session cookie they set lasts a
week.

Operator-only endpoints (tenant management) sit at /ui/tenants and
/ui/tenant/{id}/update. Tenant-scoped data routes (/ui/dial,
/ui/history, /ui/calls/live, /ui/result, /ui/audio) work for either
role and self-scope based on session.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Optional

from . import db
import fastapi
from fastapi import Cookie, Form, Request, status
from fastapi.responses import (
    FileResponse,
    HTMLResponse,
    JSONResponse,
    RedirectResponse,
)
from fastapi.templating import Jinja2Templates

from . import ratelimit, tenants, voices
from .business_agent import BusinessCallSpec
from .sessions import (
    COOKIE_MAX_AGE,
    COOKIE_NAME,
    decode_role,
    encode_role,
    is_operator,
    role_tenant_id,
    verify_magic_token,
)

log = logging.getLogger(__name__)

_HERE = Path(__file__).parent
templates = Jinja2Templates(directory=str(_HERE / "templates"))

router = fastapi.APIRouter(prefix="/ui", tags=["ui"])


# Secure cookies by default (the dashboard is served over HTTPS in prod via the
# tunnel / Render). Set INSECURE_COOKIES=1 only for local HTTP dev.
_COOKIE_SECURE = os.environ.get("INSECURE_COOKIES", "").strip().lower() not in (
    "1", "true", "yes",
)


def _set_cookie(response: fastapi.Response, role: str) -> None:
    response.set_cookie(
        COOKIE_NAME,
        encode_role(role),
        httponly=True,
        secure=_COOKIE_SECURE,
        max_age=COOKIE_MAX_AGE,
        samesite="strict",
    )


def _current_role(request: Request) -> Optional[str]:
    return decode_role(request.cookies.get(COOKIE_NAME))


async def _require_session(request: Request) -> str:
    role = _current_role(request)
    if not role:
        raise fastapi.HTTPException(
            status_code=status.HTTP_307_TEMPORARY_REDIRECT,
            headers={"Location": "/ui/login"},
        )
    return role


async def _require_operator(request: Request) -> None:
    role = _current_role(request)
    if not is_operator(role):
        raise fastapi.HTTPException(status_code=403, detail="operator only")


# ─── Auth pages ───────────────────────────────────────────

@router.get("/login", response_class=HTMLResponse)
async def login_form(request: Request, error: Optional[str] = None):
    return templates.TemplateResponse(
        request, "login.html", {"error": error}
    )


@router.post("/login")
async def login_submit(token: str = Form(...)):
    expected = os.environ.get("BRIDGE_API_KEY", "").strip()
    if not expected or token != expected:
        return RedirectResponse(
            "/ui/login?error=invalid+access+token",
            status_code=status.HTTP_303_SEE_OTHER,
        )
    response = RedirectResponse("/ui", status_code=status.HTTP_303_SEE_OTHER)
    _set_cookie(response, "operator")
    return response


@router.get("/auth")
async def magic_auth(token: str):
    """Consume a magic-link token and set a tenant session cookie."""
    role = verify_magic_token(token)
    if not role or not role.startswith("tenant:"):
        return RedirectResponse(
            "/ui/login?error=link+expired+or+invalid",
            status_code=status.HTTP_303_SEE_OTHER,
        )
    tenant_id = role_tenant_id(role)
    if tenant_id is None:
        return RedirectResponse(
            "/ui/login?error=invalid+tenant",
            status_code=status.HTTP_303_SEE_OTHER,
        )
    # Verify the tenant still exists and is active.
    tenant = await tenants.get_tenant_by_id(tenant_id)
    if not tenant or not tenant.get("is_active", 1):
        return RedirectResponse(
            "/ui/login?error=tenant+disabled",
            status_code=status.HTTP_303_SEE_OTHER,
        )
    response = RedirectResponse("/ui", status_code=status.HTTP_303_SEE_OTHER)
    _set_cookie(response, role)
    return response


@router.get("/logout")
async def logout():
    response = RedirectResponse("/ui/login", status_code=status.HTTP_303_SEE_OTHER)
    response.delete_cookie(COOKIE_NAME)
    return response


# ─── Dashboard ───────────────────────────────────────────

@router.get("", response_class=HTMLResponse)
async def dashboard_root(request: Request):
    role = _current_role(request)
    if not role:
        return RedirectResponse("/ui/login", status_code=status.HTTP_303_SEE_OTHER)

    tenant_id = role_tenant_id(role)
    operator = is_operator(role)
    viewer_name = "operator"
    quota_used = None
    quota_limit = None

    if tenant_id is not None:
        tenant = await tenants.get_tenant_by_id(tenant_id)
        if not tenant or not tenant.get("is_active", 1):
            return RedirectResponse(
                "/ui/login?error=tenant+disabled",
                status_code=status.HTTP_303_SEE_OTHER,
            )
        viewer_name = tenant["name"]
        quota_limit = tenant.get("custom_calls_per_day") or ratelimit.DEFAULT_DAILY_QUOTA
        quota_used = await tenants.count_calls_today(tenant_id)

    return templates.TemplateResponse(
        request,
        "dashboard.html",
        {
            "bridge_host": request.headers.get("host", "127.0.0.1:8082"),
            "viewer_name": viewer_name,
            "is_operator": operator,
            "tenant_id": tenant_id,
            "quota_used": quota_used,
            "quota_limit": quota_limit,
        },
    )


@router.get("/", include_in_schema=False)
async def dashboard_slash(request: Request):
    return await dashboard_root(request)


# ─── Browser-fetched JSON (cookie-authed) ────────────────

@router.get("/calls/live", dependencies=[fastapi.Depends(_require_session)])
async def ui_calls_live(request: Request) -> dict:
    from .bridge import _ACTIVE, _PENDING, _PENDING_LOCK, _snapshot_call

    role = _current_role(request)
    tenant_id = role_tenant_id(role)
    async with _PENDING_LOCK:
        ringing = [_snapshot_call(s, phase_override="ringing") for s in _PENDING.values()]
        active = [_snapshot_call(s) for s in _ACTIVE.values()]
    calls = ringing + active
    if tenant_id is not None:
        calls = [c for c in calls if c.get("tenant_id") == tenant_id]
    calls.sort(key=lambda c: c.get("started_at", 0), reverse=True)
    return {"ok": True, "count": len(calls), "calls": calls}


@router.get("/result/{room}", dependencies=[fastapi.Depends(_require_session)])
async def ui_result(request: Request, room: str) -> dict:
    """Tenant-safe wrapper for /result/{room}. Tenants can only see their own."""
    role = _current_role(request)
    tenant_id = role_tenant_id(role)
    if tenant_id is not None:
        call = await tenants.get_call(room)
        if not call or call.get("tenant_id") != tenant_id:
            return {"status": "missing", "room": room}
    # Delegate to the same logic the public /result uses.
    from .bridge import get_result
    return await get_result(room)


@router.get("/history", dependencies=[fastapi.Depends(_require_session)])
async def ui_history(request: Request, limit: int = 30) -> dict:
    """Tenants: own calls only. Operator: every call across the bridge."""
    role = _current_role(request)
    tenant_id = role_tenant_id(role)
    limit = max(1, min(limit, 200))
    cols = (
        "SELECT room, tenant_id, destination, task, language, business_name, "
        "started_at, ended_at, status, answer, confidence, duration_seconds, "
        "answered_by, twilio_call_status FROM calls "
    )
    if tenant_id is not None:
        rows = await db.fetch_all(
            cols + "WHERE tenant_id = :tid ORDER BY started_at DESC LIMIT :lim",
            tid=tenant_id, lim=limit,
        )
    else:
        rows = await db.fetch_all(
            cols + "ORDER BY started_at DESC LIMIT :lim", lim=limit,
        )
    return {"ok": True, "count": len(rows), "calls": rows}


@router.post("/dial", dependencies=[fastapi.Depends(_require_session)])
async def ui_dial(request: Request, payload: dict) -> dict:
    """Dispatch from the browser. Tenant_id is forced from the session —
    a tenant can't dial on someone else's behalf even by crafting payload."""
    from .bridge import dispatch_gradbot_call

    role = _current_role(request)
    tenant_id = role_tenant_id(role)

    raw_to = payload.get("to", "")
    normalised_to = "+" + "".join(ch for ch in str(raw_to) if ch.isdigit())
    if normalised_to == "+":
        return {"ok": False, "error": "destination must contain digits"}

    if tenant_id is not None:
        ok, reason = await ratelimit.reserve(tenant_id)
        if not ok:
            return {"ok": False, "error": reason}

    spec = BusinessCallSpec(
        task=payload.get("reason", ""),
        language=(payload.get("language") or "en").lower(),
        business_name=payload.get("business_name", ""),
        destination=normalised_to,
        allow_booking=bool(payload.get("allow_booking", False)),
    )
    out = await dispatch_gradbot_call(to=normalised_to, spec=spec, tenant_id=tenant_id)
    if out.startswith("Error:"):
        ratelimit.release(tenant_id)
        return {"ok": False, "error": out}
    return {"ok": True, "room": out}


@router.get("/audio/{room}", dependencies=[fastapi.Depends(_require_session)])
async def ui_audio(request: Request, room: str):
    from .bridge import RECORDINGS_ROOT

    role = _current_role(request)
    tenant_id = role_tenant_id(role)

    safe = "".join(ch for ch in room if ch.isalnum() or ch in "_-")
    if not safe or safe != room:
        raise fastapi.HTTPException(status_code=400, detail="bad room")

    if tenant_id is not None:
        call = await tenants.get_call(safe)
        if not call or call.get("tenant_id") != tenant_id:
            raise fastapi.HTTPException(status_code=404, detail="not yours")

    base = RECORDINGS_ROOT / safe
    for candidate in ("mixed.wav", "tts_direct.wav", "sip_caller.wav"):
        path = base / candidate
        if path.exists():
            return FileResponse(path, media_type="audio/wav", filename=f"{safe}-{candidate}")
    raise fastapi.HTTPException(status_code=404, detail="no audio yet")


# ─── Voice clone (tenant or operator) ─────────────────

@router.get("/voice", dependencies=[fastapi.Depends(_require_session)])
async def ui_voice_status(request: Request) -> dict:
    """Return the tenant's current voice clone metadata, or None."""
    role = _current_role(request)
    tenant_id = role_tenant_id(role)
    if tenant_id is None:
        return {"ok": True, "voice_id": None, "voice_name": None, "scope": "operator"}
    t = await tenants.get_tenant_by_id(tenant_id)
    return {
        "ok": True,
        "voice_id": (t or {}).get("voice_id"),
        "voice_name": (t or {}).get("voice_name"),
        "scope": "tenant",
    }


@router.post("/voice", dependencies=[fastapi.Depends(_require_session)])
async def ui_voice_upload(request: Request, audio: fastapi.UploadFile = fastapi.File(...)):
    """Upload an audio sample, create a Gradium voice clone, attach to tenant.

    Operator uploads aren't attached anywhere — they just return the UID for
    the operator to wire elsewhere. Tenant uploads replace any existing
    voice on their account.
    """
    role = _current_role(request)
    tenant_id = role_tenant_id(role)

    blob = await audio.read()
    suffix = Path(audio.filename or "audio.bin").suffix or ".ogg"
    label = (audio.filename or "voice").rsplit(".", 1)[0][:60]

    if tenant_id is not None:
        t = await tenants.get_tenant_by_id(tenant_id)
        clone_name = f"gradphone:{t['name']}" if t else f"gradphone:tenant-{tenant_id}"
    else:
        clone_name = f"gradphone:operator:{label}"

    try:
        result = await voices.clone_from_bytes(
            blob, name=clone_name, suffix=suffix,
            description="Voice clone from gradphone upload",
        )
    except Exception as e:  # noqa: BLE001
        log.exception("voice clone failed")
        return JSONResponse({"ok": False, "error": str(e)}, status_code=400)

    uid = result.get("uid") or result.get("voice_id") or result.get("id")
    if not uid:
        return JSONResponse({"ok": False, "error": f"unexpected Gradium response: {result}"}, status_code=502)

    if tenant_id is not None:
        await tenants.set_tenant_voice(tenant_id, uid, voice_name=clone_name)

    return {"ok": True, "voice_id": uid, "voice_name": clone_name, "raw": result}


@router.post("/voice/clear", dependencies=[fastapi.Depends(_require_session)])
async def ui_voice_clear(request: Request) -> dict:
    """Remove the tenant's voice clone — calls revert to the language default."""
    role = _current_role(request)
    tenant_id = role_tenant_id(role)
    if tenant_id is None:
        return {"ok": False, "error": "operators have no per-account voice"}
    t = await tenants.get_tenant_by_id(tenant_id)
    old_uid = (t or {}).get("voice_id")
    await tenants.set_tenant_voice(tenant_id, "", "")
    # Best-effort: delete the clone server-side. Non-fatal on failure.
    if old_uid:
        await voices.delete_voice(old_uid)
    return {"ok": True, "cleared": bool(old_uid)}


# ─── Tenant management (operator only) ────────────────

@router.get("/tenants", dependencies=[fastapi.Depends(_require_operator)])
async def ui_tenants_list() -> dict:
    rows = await tenants.list_tenants()
    # Annotate each tenant with today's call count.
    out = []
    for t in rows:
        today = await tenants.count_calls_today(t["id"])
        in_flight = ratelimit.in_flight_count(t["id"])
        out.append({**t, "calls_today": today, "in_flight": in_flight,
                    "effective_quota": t.get("custom_calls_per_day") or ratelimit.DEFAULT_DAILY_QUOTA})
    return {"ok": True, "count": len(out), "tenants": out}


@router.post("/tenants/{tid}/update", dependencies=[fastapi.Depends(_require_operator)])
async def ui_tenant_update(tid: int, payload: dict) -> dict:
    """Set is_active and/or custom_calls_per_day for a tenant."""
    fields = []
    params: dict = {}
    if "is_active" in payload:
        fields.append("is_active = :is_active")
        params["is_active"] = 1 if payload["is_active"] else 0
    if "custom_calls_per_day" in payload:
        v = payload["custom_calls_per_day"]
        if v in (None, "", 0):
            fields.append("custom_calls_per_day = NULL")
        else:
            try:
                params["ccpd"] = int(v)
                fields.append("custom_calls_per_day = :ccpd")
            except (TypeError, ValueError):
                return {"ok": False, "error": "custom_calls_per_day must be an int or null"}
    if not fields:
        return {"ok": False, "error": "nothing to update"}
    params["id"] = tid
    await db.execute(f"UPDATE tenants SET {', '.join(fields)} WHERE id = :id", **params)
    return {"ok": True}
